/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.ArrayList;
import java.util.Scanner;
import java.util.Stack;
import javax.swing.JFileChooser;
import java.io.*;
import java.util.*;
import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVParser;


/**
 *
 * @author Eric Wang
 */

public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jButton3 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setText("Club Calculator");

        jButton1.setText("Calculate");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("X");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Monday");

        jLabel3.setText("Tuesday");

        jLabel4.setText("Wendsday");

        jLabel5.setText("Thursday");

        jLabel6.setText("Friday");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jScrollPane4.setViewportView(jTextArea4);

        jButton3.setText("Select FIle");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Clubs");

        jLabel8.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel8.setText("Course Calculator");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jTextArea5.setColumns(20);
        jTextArea5.setRows(5);
        jScrollPane5.setViewportView(jTextArea5);

        jButton4.setText("Select Course Plan");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Calculate");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Select Student Selection");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addGap(104, 104, 104)
                .addComponent(jLabel3)
                .addGap(90, 90, 90)
                .addComponent(jLabel4)
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(239, 239, 239)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(258, 258, 258))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(288, 288, 288)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(339, 339, 339)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(359, 359, 359)
                        .addComponent(jLabel7))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(335, 335, 335)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel1))
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            calculateClub();
            jTextField1.setText("Completed");
        } catch (Exception ea){
            jTextField1.setText("ERROR");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
    
    java.io.File file;
    
    JFileChooser fileChooser = new JFileChooser();
    public void openFile()throws Exception{
        if(fileChooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            file = fileChooser.getSelectedFile();
            Scanner input = new Scanner(file);
            //put input code here
            input.close();
        } else {
            
        }
    }
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try {
            openFile();
            jTextField1.setText("File Accepted");
        } catch (Exception e){
            jTextField1.setText("ERROR");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        Main coursecalc = new Main();
        try {
            coursecalc.calcCourse(file1,file2);
            jTextField2.setText("Completed");
        } catch (Exception ea){
            jTextField2.setText("ERROR");
        }
    }//GEN-LAST:event_jButton5ActionPerformed
    java.io.File file1;
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try {
        if(fileChooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            file1 = fileChooser.getSelectedFile();
            Scanner input = new Scanner(file1);
            //put input code here
            String [] firstLine = input.nextLine().split(" ");
            for(int i=1; i<firstLine.length; i++) {
                clubs.add(firstLine[i]);
            }
            while(input.hasNextLine()) {
                String [] line = input.nextLine().split(" ");
                for(int i=1; i<line.length; i++) {
                    for(int j=i+1; j<line.length; j++) {
                        duplicates[i][j] += 1;
                    }
                }
                
            }
            input.close();
            jTextField2.setText("Accepted");
        } 
            
        }catch (Exception ea){
            jTextField2.setText("ERROR");
    }                                        
        
    }//GEN-LAST:event_jButton4ActionPerformed
    java.io.File file2;
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try {
        if(fileChooser.showOpenDialog(null)==JFileChooser.APPROVE_OPTION){
            file2 = fileChooser.getSelectedFile();
            Scanner input = new Scanner(file2);
            //put input code here
            input.close();
            jTextField2.setText("Accepted 2");
        } 
            
        }catch (Exception eb){
            jTextField2.setText("ERROR");
    }//GEN-LAST:event_jButton6ActionPerformed
    
    }
   int [][] duplicates;
   Stack<String>[]days = new Stack[10];
   ArrayList<String>clubs;
   int best;
   int sum;
   int [] clubDays;
   int n;
   public void calculateClub () throws Exception {
       //math, physics, art
       //10,7,15
       //math + physics = 3, art + math = 4, art + physics = 1;
       //clubs = new ArrayList<>();
       sum = 0;
       duplicates = arrayGenerator(clubList());
       
       /*
       n = 6;
       clubs.add("compisci");
       clubs.add("math");
       clubs.add("physics");
       clubs.add("art");
       clubs.add("engineering");
       clubs.add("literature");
       sum = 446;
       duplicates = new int[6][6];
       duplicates[0][1] = 63;
       duplicates[0][2] = 38;
       duplicates[0][3] = 23;
       duplicates[0][4] = 23;
       duplicates[0][5] = 27;
       duplicates[1][2] = 38;
       duplicates[1][3] = 23;
       duplicates[1][4] = 23;
       duplicates[1][5] = 27;
       duplicates[2][3] = 25;
       duplicates[2][4] = 27;
       duplicates[2][5] = 32;
       duplicates[3][4] = 25;
       duplicates[3][5] = 25;
       duplicates[4][5] = 27;
       */
       for(int i=0; i<n; i++) {
           for(int j=0; j<n; j++) {
               System.out.print(duplicates[i][j]+" ");
           }
           System.out.println();
       }
       //clubs.add("Math Club");
       //clubs.add("Physics Club");
       //clubs.add("Art Club");
       //duplicates[0][1] = 3;
       //duplicates[1][0] = 3;
       //duplicates[1][2] = 1;
       //duplicates[2][1] = 1;
       //duplicates[0][2] = 4;
       //duplicates[2][0] = 4;
       days = new Stack[10];
       clubDays = new int[n];
       best = 0;
       for(int i=0; i<10; i++) {
           days[i] = new Stack<>();
       }
       days[0].push(clubs.get(0));
       clubDays[0] = 0;
       search(0,clubs.get(0),0);
           //days[i].pop();
       String [] dates = {"Monday","Tuesday","Wednesday","Thursday","Friday"};
       //monday
       String [] arr = new String[days[5].size()];
        int index = days[5].size()-1;
        //System.out.println(index);
        while(!days[5].isEmpty()) {
            arr[index] = days[5].pop();
            index --;
        }
        for(int j=0; j<arr.length; j++) {
            jTextArea1.append(arr[j]+"\n");
        }
        
        //tuesday
        arr = new String[days[6].size()];
        index = days[6].size()-1;
        //System.out.println(index);
        while(!days[6].isEmpty()) {
            arr[index] = days[6].pop();
            index --;
        }
        for(int j=0; j<arr.length; j++) {
            jTextArea2.append(arr[j]+"\n");
        }
        
        //wednesday
        arr = new String[days[7].size()];
        index = days[7].size()-1;
        //System.out.println(index);
        while(!days[7].isEmpty()) {
            arr[index] = days[7].pop();
            index --;
        }
        for(int j=0; j<arr.length; j++) {
            jTextArea3.append(arr[j]+"\n");
        }
        
        //thursday
        arr = new String[days[8].size()];
        index = days[8].size()-1;
        //System.out.println(index);
        while(!days[8].isEmpty()) {
            arr[index] = days[8].pop();
            index --;
        }
        for(int j=0; j<arr.length; j++) {
            jTextArea4.append(arr[j]+"\n");
        }
        
        //friday
        arr = new String[days[9].size()];
        index = days[9].size()-1;
        //System.out.println(index);
        while(!days[9].isEmpty()) {
            arr[index] = days[9].pop();
            index --;
        }
        for(int j=0; j<arr.length; j++) {
            jTextArea5.append(arr[j]+"\n");
        }
       System.out.println("Best amount satisfied: "+best);
       System.out.println("Total amount of duplicates: "+sum);
   }
   public void search (int index, String club, int dayNum) {
       //get next element in hash map
       if(best == sum) {
           return;
       }
       if(index >= clubs.size()-1) {
           int satisfied = satisfiedCount();
           String [] dates = {"Monday","Tuesday","Wednesday","Thursday","Friday"};
           if(satisfied>best) {
               best = satisfied;
               //System.out.println(best);
               for(int i=0; i<5; i++) {
                   days[i + 5] = (Stack<String>) days[i].clone();
                   //System.out.println(days[i + 5].size());
               }
           }
           days[dayNum].pop();
           return;
       }
       String next = clubs.get(index+1);
       //System.out.println(next);
       for(int i=0; i<5; i++) {
           days[i].push(next);
           clubDays[index+1] = i;
           search(index+1,next,i);
       }
       days[dayNum].pop();

   }
   public int satisfiedCount () {
       int counter = 0;
       for(int i=0; i<n; i++) {
           for(int j=0; j<n; j++) {
               String club1 = clubs.get(i);
               String club2 = clubs.get(j);

               if(clubDays[i]!= clubDays[j]) counter += duplicates[i][j];
           }
       }
       return counter;
   }
   public ArrayList<String> clubList() {
       String[]club = {"Compsci","Math","Physics", "Art", "Engineering", "DECA", "Debate", "RASA", "Greenhouse", "Chess", "Robotics", "Badminton", "Anime", "HOSA", "E-Sports"};
       clubs = new ArrayList<>();
       n = (int)(Math.random()*5)+6;
       for(int i=0; i<n; i++) {
           clubs.add(club[i]);
       }
       return clubs;
   }
   public int[][] arrayGenerator(ArrayList<String>arr) {
       int [][] dupe = new int[n][n];
       for(int i=0; i<n; i++) {
           for(int j=i+1; j<n; j++) {
               int x = (int)(Math.random()*10);
               dupe[i][j] = x;
               sum+= x;
           }
       }
       return dupe;
   }

   public void readFromExcel () throws Exception{
        String fileNameDefined = "";
        // -File class needed to turn stringName to actual file
        File file = new File(fileNameDefined);
        
        
            // -read from filePooped with Scanner class
            Scanner inputStream = new Scanner(file);
            String []data = inputStream.next().split(",");
                for(int i=1; i<data.length; i++) {
                    clubs.add(data[i]);
                }
                System.out.println(data + "***");
            // hashNext() loops line-by-line
            while(inputStream.hasNext()){
                //read single line, put in string
                
                

            }
            // after loop, close scanner
            inputStream.close();
    }   
   
  

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }
    
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables

}